apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: flan-example-is
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: caikit
      name: ''
      resources:
        limits:
          cpu: '2'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      # Defined in caikit_tgis_servingruntime.yaml
      runtime: <sr-resource-name>
      storage:
        # Defined in s3-secret.yaml
        key: <secret-name-for-bucket-connection>
        path: <path-to-model-from-bucket-root>
